# Generated by Django 5.0.1 on 2024-02-08 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(default=datetime.datetime(2024, 2, 8, 21, 54, 38, 886041, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(default=datetime.datetime(2024, 2, 8, 21, 54, 38, 886265, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
